---
- hosts: all
  tasks:
  - name: make sure all nodes are online
    ping:

- hosts: etcd
  tasks:
  - name: stop the etcd service on the etcd nodes
    service: 
      name: etcd
      state: stopped

- hosts: kubernetes
  tasks:
  - name: stop the kubelet service on the kubernetes nodes
    service:
      name: kubelet
      state: stopped

- hosts: docker
  tasks:
    - name: does the machine have docker?
      shell: rpm -q docker 
      register: has_docker
    - name: stop all running docker containers
      shell: 'sudo docker stop $(sudo docker ps -a -q)'
      when: has_docker.rc == 0