---
- hosts: all
  gather_facts: no
  tasks:
  - name: make sure all nodes are online
    ping:

- hosts: etcd
  gather_facts: no
  tasks:
  - name: stop the etcd service on the etcd nodes
    service: 
      name: etcd
      state: stopped

- hosts: kubernetes
  gather_facts: no
  tasks:
  - name: stop the kubelet service on the kubernetes nodes
    service:
      name: kubelet
      state: stopped

- hosts: docker
  gather_facts: no
  tasks:
    - name: does the machine have docker?
      shell: which docker
      register: has_docker
      ignore_errors: yes
    - name: stop all running docker containers
      shell: 'sudo docker stop $(sudo docker ps -a -q)'
      when: has_docker.rc == 0
      ignore_errors: yes
    - name: kill all docker containers
      shell: 'sudo docker kill $(sudo docker ps -a -q)'
      when: has_docker.rc == 0
      ignore_errors: yes
    - name: remove all docker containers
      shell: 'sudo docker rm $(sudo docker ps -a -q)'
      when: has_docker.rc == 0
      ignore_errors: yes
    - name: uninstall docker
      yum:
        name: docker*
        state: removed

- hosts: etcd
  gather_facts: no
  tasks:
    - name: uninstall etcd
      yum:
        name: etcd*
        state: removed

- hosts: kubernetes
  gather_facts: no
  tasks: 
    - name: uninstall kubernetes
      yum:
        name: kube*
        state: removed
    - name: remove kubernetes configuration
      file:
        path: /etc/kubernetes
        state: absent

- hosts: all
  gather_facts: no
  tasks:
    - name: remove glusterfs
      yum:
        name: gluster*
        state: removed
    - name: remove gluster image file
      file:
        path: ~/gluster*.img
        state: absent

- hosts: lb
  gather_facts: no
  tasks:
    - name: remove haproxy
      yum:
        name: haproxy*
        state: removed

- hosts: all
  gather_facts: no
  tasks:
    - name: put selinux in permissive mode
      selinux:
        policy: targeted
        state: permissive
    - name: stop firewall
      service:
        name: firewalld
        state: stopped
    - name: reboot machines
      reboot: