---
- hosts: all
  gather_facts: "{{ gather_facts }}"
  tasks:
  - name: make sure all nodes are online
    ping:

- hosts: etcd
  gather_facts: "{{ gather_facts }}"
  tasks:
  - name: stop the etcd service on the etcd nodes
    service: 
      name: etcd
      state: stopped

- hosts: kubernetes
  gather_facts: "{{ gather_facts }}"
  tasks:
  - name: stop the kubelet service on the kubernetes nodes
    service:
      name: kubelet
      state: stopped

- hosts: docker
  gather_facts: "{{ gather_facts }}"
  tasks:
    - name: does the machine have docker?
      shell: which docker
      register: has_docker
      ignore_errors: yes
    - name: stop all running docker containers
      shell: 'sudo docker stop $(sudo docker ps -a -q)'
      when: has_docker.rc == 0
      ignore_errors: yes
    - name: kill all docker containers
      shell: 'sudo docker kill $(sudo docker ps -a -q)'
      when: has_docker.rc == 0
      ignore_errors: yes
    - name: remove all docker containers
      shell: 'sudo docker rm $(sudo docker ps -a -q)'
      when: has_docker.rc == 0
      ignore_errors: yes
    - name: uninstall docker
      yum:
        name: docker*
        state: removed